image: docker

services:
  - docker:dind

variables:
  SHARED_PATH: /builds/$CI_PROJECT_PATH/shared

geocoder-tester-cosmogony:
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - export OSM_DIR=$SHARED_PATH/data/osm ADDR_DIR=$SHARED_PATH/data/addresses
    - apk add --no-cache python3 py3-pip git bash
    - ./ci/gitlab/init.sh
    - ./ci/gitlab/download_data.sh
  script:
    - cd docker_mimir
    - inv -f import_settings_with_cosmogony.yml load-in-docker-and-test --files docker-compose.build.yml
  artifacts:
    expire_in: 2 weeks
    paths:
      - docker_mimir/results
  tags:
    - france_cosmogony

geocoder-tester-osm-admins:
  before_script:
    - export OSM_DIR=$SHARED_PATH/data/osm ADDR_DIR=$SHARED_PATH/data/addresses
    - apk add --no-cache python3 py3-pip git bash
    - ./ci/gitlab/init.sh
    - ./ci/gitlab/download_data.sh
  script:
    - cd docker_mimir
    - inv -f import_settings_without_cosmogony.yml load-in-docker-and-test --files docker-compose.build.yml
  artifacts:
    expire_in: 2 weeks
    paths:
      - docker_mimir/results
  tags:
    - france_osm_admins


