# Configuration for osm2mimir
# Since this is the default configuration, which is embedded in the code,
# you should rebuild mimirsbrunn if you change a value in this file.

dataset = "fr"

[elasticsearch]
  connection_string = "http://localhost:9200/munin"
  insert_thread_count = 1
  streets_shards = 2
  streets_replicas = 1
  admins_shards = 1
  admins_replicas = 1
  pois_shards = 1
  pois_replicas = 1

[admin]
  import = false
  city_level = 8
  levels = []

[poi]
  import = false

[way]
  import = false
  [way.exclusion]
    # See [OSM Key Highway](https://wiki.openstreetmap.org/wiki/Key:highway) for background.
    highways = [
      "bus_guideway",
      "bus_stop",
      "elevator",
      "escape",
      "platform"
    ]
