[[types]]
  id = "amenity:college"
  name = "École"
[[types]]
  id = "amenity:university"
  name = "Université"
[[types]]
  id = "amenity:theatre"
  name = "Théâtre"
[[types]]
  id = "amenity:hospital"
  name = "Hôpital"
[[types]]
  id = "amenity:post_office"
  name = "Bureau de poste"
[[types]]
  id = "amenity:bicycle_rental"
  name = "Station VLS"
[[types]]
  id = "amenity:bicycle_parking"
  name = "Parking vélo"
[[types]]
  id = "amenity:parking"
  name = "Parking"
[[types]]
  id = "amenity:police"
  name = "Police, gendarmerie"
[[types]]
  id = "amenity:townhall"
  name = "Mairie"
[[types]]
  id = "leisure:garden"
  name = "Jardin"
[[types]]
  id = "leisure:park"
  name = "Parc, espace vert"

[[rules]]
  type = "amenity:college"
  [[rules.osm_tags_filters]]
    key = "amenity"
    value = "college"
[[rules]]
  type = "amenity:university"
  [[rules.osm_tags_filters]]
    key = "amenity"
    value = "university"
[[rules]]
  type = "amenity:theatre"
  [[rules.osm_tags_filters]]
    key = "amenity"
    value = "theatre"
[[rules]]
  type = "amenity:hospital"
  [[rules.osm_tags_filters]]
    key = "amenity"
    value = "hospital"
[[rules]]
  type = "amenity:post_office"
  [[rules.osm_tags_filters]]
    key = "amenity"
    value = "post_office"
[[rules]]
  type = "amenity:bicycle_rental"
  [[rules.osm_tags_filters]]
    key = "amenity"
    value = "bicycle_rental"
[[rules]]
  type = "amenity:bicycle_parking"
  [[rules.osm_tags_filters]]
    key = "amenity"
    value = "bicycle_parking"
[[rules]]
  type = "amenity:parking"
  [[rules.osm_tags_filters]]
    key = "amenity"
    value = "parking"
[[rules]]
  type = "amenity:police"
  [[rules.osm_tags_filters]]
    key = "amenity"
    value = "police"
[[rules]]
  type = "amenity:townhall"
  [[rules.osm_tags_filters]]
    key = "amenity"
    value = "townhall"
[[rules]]
  type = "leisure:garden"
  [[rules.osm_tags_filters]]
    key = "leisure"
    value = "garden"
[[rules]]
  type = "leisure:park"
  [[rules.osm_tags_filters]]
    key = "leisure"
    value = "park"
