name: Release_Packages

on:
  push:
    tags:
      - '*'

jobs:

  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: jessie
            packages: pkg-config libssl-dev
            rust: 1.44.1
          - version: stretch
            packages: pkg-config libssl1.0-dev
            rust: 1.44.1
          - version: buster
            packages: pkg-config libssl-dev
            rust: 1.48.0

    container: debian:${{matrix.version}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          apt-get update
          apt-get install -y curl wget build-essential
          apt-get install -y ${{ matrix.packages }}
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Build package
        run: ./scripts/build_deb.sh ${{ matrix.version }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debian-package-release
          path: ./scripts/deb-scratch/*

      - name: slack notification (the job has failed)
        if: failure()
        run: |
          sudo apt install -y httpie
          echo '{"text":":Warning: Github Actions: build packages for branch release failed  ! (https://github.com/CanalTP/mimirsbrunn/actions/workflows/release.yml)."}' | http --json POST ${{secrets.SLACK_NAVITIA_AUTOCOMPLETE_TEAM_URL}}

  publish:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: install  dependency
        run: apt update && apt install -y httpie
      - name: run publish job & slack notification (the job has successed)
        run: |
          http --ignore-stdin -v -f POST https://${{secrets.JENKINS_TOKEN}}@jenkins-core.canaltp.fr/job/publish_autocomplete_packages/
          echo '{"text":":information_source: Github Actions: build packages for branch release succeded - New packages mimir are available"}' | http --json POST ${{secrets.SLACK_NAVITIA_AUTOCOMPLETE_TEAM_URL}}
